---
services:
  backend-cache:
    image: redis:7.4.1-alpine3.20
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: redis-server --save 20 1 --loglevel warning --requirepass "${REDIS_PASSWORD}"
    volumes:
      - ./redis-data:/root/redis
      - /etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
