### Register a user
POST https://medsync-9a76abebef65.herokuapp.com/api/auth/register
Content-Type: application/json

{
    "name": "Super Admin",
    "dateOfBirth": "1982-01-06T00:00:00.000Z",
    "password": "password",
    "role": "admin",
    "email": "admin@gmail.com"
}

### Login a user
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
    "password": "test123",
    "email": "lilbrown3000+test3@gmail.com"
}


### Get all user
GET {{BASE_URL}}/api/users
Content-Type: application/json

### Get one user payment
GET {{BASE_URL}}/api/users/13
Content-Type: application/json

### Save staff
POST {{BASE_URL}}/api/staff
Content-Type: application/json

{
    "userId": 16,
    "speciality": "Dermatology",
    "shift": "afternoon"
}

### Get all staff
GET {{BASE_URL}}/api/staff
Content-Type: application/json

### Get all appointment
GET {{BASE_URL}}/api/appointment
Content-Type: application/json

### Book an appointment
POST {{BASE_URL}}/api/appointment
Content-Type: application/json

{
    "patientId": 13,
    "doctorId": 15,
    "reason": "Sleeping disorder",
    "duration": 60
}


### Get all users appointment
GET {{BASE_URL}}/api/appointment/users/13
Content-Type: application/json

### Get all doctors appointment
GET {{BASE_URL}}/api/appointment/10
Content-Type: application/json

### Make payment
POST {{BASE_URL}}/api/payment
Content-Type: application/json

{
    "appointmentId": 22,
    "amount": 200,
    "patientId": 13
}


### Get all payment
GET {{BASE_URL}}/api/payment
Content-Type: application/json

### Get all user payment
GET {{BASE_URL}}/api/payment/10
Content-Type: application/json

### Create medical record
POST {{BASE_URL}}/api/records
Content-Type: application/json

{
  "patientId": 13,
  "doctorId": 15,
  "appointmentId": 22,
  "diagnosis": "Hypertension",
  "prescription": "Prescribed Lisinopril 10mg",
  "testResults": "pending"
}
